name: Dotnet test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: https://git.rrricardo.top/actions/checkout@v3

      - run: dotnet test